### ISSUE TITLE
Login Doesn't work

### ISSUE THREAD

**Issue by lgugliotta** [acacha/adminlte-laravel#244]
Hi!.

Sorry for my english.

I did the installation following the steps of 'Laravel 5.4 manual installation'

Besides this I had to add the following lines to AppServiceProvider so that 'php artisan migrate' work

`Schema::defaultStringLength(191);` in  public function boot()

I can register without problems and it is saved in the database.

But I'm never redirected to HOME, or registering or signing in, always return me to login or register page at the case may be.

Include as many relevant details about the environment you experienced the bug in and how to reproduce it.

* PHP 5.6.30
* Laravel 5.4

**Comment by acacha** [comment]
Sorry I don't understand:

Schema::defaultStringLength(191); in public function boot()

Why you say you need this?

**Comment by lgugliotta** [comment]
Because when I tried make 'php artisan migrate', it display this error:
    

>     [Illuminate\Database\QueryException]
>     SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table users add unique users_email_unique(email))
> 
>     [PDOException]
>     SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

**Comment by acacha** [comment]
Ok!Thanks. Which kind of database are you using? @lgugliotta

**Comment by lgugliotta** [comment]
MySQL 5.5.24, after adding those lines of code, the error disappeared and the migration worked perfectly and saves the database to the DB correctly.

In spite of this, at the time of registering, although it does the saving in DB, it does not go to HOME, even when signing in (LOGIN)

**Comment by lmvalenzuela** [comment]
This might be corrected by changing the mysql driver in `/config/database.php` change: 

```php
'charset' => 'utf8mb4',
'collation' => 'utf8mb4_unicode_ci',
```
To:
 ```php
'charset' => 'utf8',
'collation' => 'utf8_general_ci',
```
Hope this helps

**Comment by eriksonflavio** [comment]
Acacha,
I have de same problem.
I´m using Laravel 5.4, MySQL 5.6 and apply changes in config/database.php that Imvalenzuela are suggest, but de problem persist.
Have you a solution?
Thanks

**Comment by DhirajBelure** [comment]
@acacha
How the login is working in adminlte laravel? can you please, explain steps how the username and password is check from db and return to home page.

**Comment by Slaurentiu** [comment]
the problem in in php.ini: set always_populate_raw_post_data to -1.
