### ISSUE TITLE
Laravel\Dusk\DuskServiceProvider not found at fresh install after executing phunit

### ISSUE THREAD

**Issue by acacha** [acacha/adminlte-laravel#312]
Lots of test fail after executing phpunit

```
16) Tests\Unit\ExampleTest::testBasicTest
Error: Class 'Laravel\Dusk\DuskServiceProvider' not found
```

**Comment by acacha** [comment]
Solved in 5.0.1

**Comment by thgiang** [comment]
This issue still occurs. I tried Laravel and adminlte-laravel latest version.
Class 'Laravel\Dusk\DuskServiceProvider' not found

Screenshot: http://prntscr.com/iikpgn

**Comment by reidaigo** [comment]
The issue is actual, I have the same problem.
